plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'in.org.cocsit.collegeadmissionmanagementsystem'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "in.org.cocsit.collegeadmissionmanagementsystem"
        minSdk 31
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    dependenciesInfo {
        includeInApk false
        includeInBundle false
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation 'com.daimajia.androidanimations:library:2.4@aar'
    implementation 'com.daimajia.easing:library:1.0.1@aar'
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation libs.lottie
    implementation 'com.orhanobut:dialogplus:1.11@aar'
    implementation libs.pdf.viewer
    implementation libs.okhttp
}
